### ISSUE TITLE
NewsReader: feedburner feed does not work

### ISSUE THREAD

**Issue by Louis-CR** [jbe2277/waf#1]
Hello,
This feed http://feeds.feedburner.com/lesnumeriques/news is not working.

Can you check please ? 
Thanks.

**Comment by jbe2277** [comment]
I was able to reproduce this issue.

Unfortunately, this seems to be a bug in the Microsoft [SyndicationClient.RetrieveFeedAsync](https://msdn.microsoft.com/library/windows/apps/windows.web.syndication.syndicationclient.retrievefeedasync.aspx) API.

**Comment by jbe2277** [comment]
This issue has been fixed in NewsReader version 4.0.8.
