### ISSUE TITLE
DelegateCommand not usable with vb.net

### ISSUE THREAD

**Issue by jonsen-hu** [jbe2277/waf#11]
Hi,

im using your Framework for a vb.net project.

the DelegateCommand isnt usable dont know why, the events simply wont fire.
And since the fields are private that class isnt extendable.

I think the problem is, that the Action in vb.net isnt castable from Null, but im not completely sure.

Could you please make them protected, so at least it would be possible to override them.

thanks in advance and thanks for this nice framework too.

greetings
jonas

**Comment by jbe2277** [comment]
The `DelegateCommand` works perfectly fine with VB.NET.
```VB
TestCommand = New DelegateCommand(Sub() MessageBox.Show("Test"))
```

**Comment by jonsen-hu** [comment]
Thats true, the execution of the command works.

But the canexecutechange event is never called and the raisecanexecutechangemethod has no effect. Simple comnmands work.

thanks for the feedback
