### ISSUE TITLE
IFileDialogService can't import

### ISSUE THREAD

**Issue by Sunng210** [jbe2277/waf#13]
I write a demo to try WAF, when I try to use FileDialog, I used  IFileDialogService, but it throw an exception, it says can't find the export ContractName="System.Waf.Applications.Services.IFileDialogService".

This is my import code.
[ImportingConstructor]
        public ShellViewModel(IShellView view, IFileDialogService fileDialogService)
            : base(view)
        {
            exitCommand = new DelegateCommand(Close);
            fileDialogService = this.fileDialogService;
        }

Thanks.

**Comment by jbe2277** [comment]
This error comes when the `System.Waf.Wpf` assembly is not registered via MEF. Add the following line:

https://github.com/jbe2277/waf/blob/7e33fc81709bd0e296da001613ec70d2f1861616/src/System.Waf/Samples/Writer/Writer.Presentation/App.xaml.cs#L72
