### ISSUE TITLE
WafWinFormsAdapter project

### ISSUE THREAD

**Issue by yletallec** [jbe2277/waf#21]
Hi,
I'm looking for the WAF WinForms Adapter project using the MVVM pattern and providing a WinForms and a WPF Presentation layer which can be exchanged. How to get it ?
[jbe](https://stackoverflow.com/users/103988/jbe)
 [Dec 4, 2011 at 19:27](https://stackoverflow.com/questions/8268408/restructure-win-forms-application-to-mvvp-pattern-possible-future-wpf-version/8268700#comment10339327_8268408)

**Comment by jbe2277** [comment]
Unfortunately, the code is not available anymore. The code was hosted on Microsoft's open source code platform CodePlex. After the platform was shutdown the code is gone.

Anyway, this code was only experimental and now more than 10 years old. I suggest to search for a more recent solution.

See https://web.archive.org/web/20150402064709/http://waf.codeplex.com/releases/view/52583

**Comment by yletallec** [comment]
Thank you very much for your quick answer. Fyi, the link points to an unavailable ressource:

![image](https://user-images.githubusercontent.com/9073846/167803915-3fcd90a2-ded2-4fc9-9f4b-8fda856981c6.png)
Do you still have a copy of **WafWinFormsAdapter-1.0.0.1.zip**?

**Comment by jbe2277** [comment]
Unfortunately, WafWinFormsAdapter-1.0.0.1.zip is not available anymore.

**Comment by yletallec** [comment]
It could be found here I guess:

https://github.com/Blind-Striker/baldursgatepartygold/tree/master/ExternalProjects/WafWinFormsAdapter
