### ISSUE TITLE
How to implement Undo/Redo features

### ISSUE THREAD

**Issue by abbas2012** [jbe2277/waf#4]
Hi, 
I am using version 3.0.0440 mainly because my application is designed as database first.  It seems I cannot add new discussion on CodePlex.

Can you please give me an idea of the best practice for implementing undo/redo features in the BookLibrary? The one provided is for the DataGrid cell before the focus is lost.

Many thanks in advance.

**Comment by jbe2277** [comment]
I will try to answer your questions:
- Microsoft is in the process to shutdown CodePlex. Therefore, no new discussions or issues can be started at CodePlex anymore.
- WAF has no impact on how you design your database access. So, you could use the latest version of the WAF libraries.
- Undo/Redo: I have implemented the limited undo/redo support of WPF and the DataGrid. A full working undo/redo feature is no trivial task and has a major impact on the application design. Please search the internet for samples.

**Comment by abbas2012** [comment]
Mnay thanks for your resply and suggestions.

Actually, I had already done the search and the most relevant article I found was in https://danicalbet.wordpress.com/2009/01/30/viewmodelling-lists/  with an example code in https://github.com/danice/MVVMUndoRedo/tree/master. 

However, before trying to implement that I thought I seek your advice first.  Basically, from what I could follow, this approach creates a mirror list of the viewmodel collections in a class called 'VMAgenda', and then performs the undo/redo operations on the mirrored list.

So, in the BookLibrary sample, 'ICollection<BookListViewModel> BooksLists', generated in the VMAgenda class, includes mirror list of Books data model (BookDataModel).

The VMAgenda is instantiated in the BookListView's code behind and then set as the DataContext:

       public BookListView(CompositionContainer container, IEntityService entityService)
        {
            InitializeComponent();

            viewModel = new Lazy<BookListViewModel>(() => ViewHelper.GetViewModel<BookListViewModel>(this));
            Loaded += FirstTimeLoadedHandler;

            this.container = container;
            this.entityService = entityService;
        }

        private void FirstTimeLoadedHandler(object sender, RoutedEventArgs e)
        {
            Loaded -= FirstTimeLoadedHandler;
            
            if (!WafConfiguration.IsInDesignMode)
            {
                bookListView = container.GetExportedValue<IBookListView>();

                bookDataModels = new SynchronizingCollection<BookDataModel, Book>
                    (entityService.Books, b => new BookDataModel(b, null));

                vmAgenda = new VMAgenda(bookListView, bookDataModels, entityService);

                DataContext = vmAgenda;
		
		...
            }
        }

I have implemented the above but clearly it does not work because the DataContext is set to BookListViewModel in ViewModel of the WAF library and resetting in the code behind does not work.

Obviously, it is a better practice to instantiate vmAgenda in the BookController class (which I can do), and set the DataContext accordingly (in the WAF library, perhaps?)

In above article, a Listbox is used to dispaly data, as shown in the follwing XAML;

	<Windows ...
	...
	    <Window.Resources>
        
		<DataTemplate DataType="{x:Type vm:BookListViewModel}">
            
			<StackPanel Orientation="Horizontal">
                
				<Label Margin="5,0,0,0" Content="{Binding Author}"/>
                
				...           
			</StackPanel>
        
		</DataTemplate>
    
	    </Window.Resources>

	...

    <StackPanel Orientation="Horizontal" undoredo:CreateCommandContext.Context="{Binding}">        
        
	<StackPanel Orientation="Vertical">
            
		<ListBox ItemsSource="{Binding BooksLists}" />
        
	</StackPanel>
  
    </StackPanel>


I am well ware that undo/redo functionality is not a trivial matter; but I would highly appreciate it if you can help me to complete the task, as I think I have reached a point that with some guidelines I can achieve that.

Many thanks in advance.

Abbas
