### ISSUE TITLE
this missing for extension method?

### ISSUE THREAD

**Issue by coumarc9** [jbe2277/waf#5]
I think there's a "this" missing in the method signature. Is it an error?
Thank you

https://github.com/jbe2277/waf/blob/2790327a0c461427ce148002b2e99316b0567ac0/src/System.Waf/System.Waf/System.Waf.Core/Foundation/CollectionHelper.cs#L57

**Comment by jbe2277** [comment]
No, the `this` is not missing here. I use the extension method syntax only for the most important helper methods. Keep the IntelliSense list clean :smiley:. The `GetNextElementOrDefault` method is not that important.

Thank you for the feedback.

**Comment by coumarc9** [comment]
Hi,
I would like to help you with those changes. I really appreciate this framework. Do you still refuse contributions?

**Comment by jbe2277** [comment]
Yes, I still refuse contributions.
 
Resolving this issue is not much effort - but I'm still not 100% convinced that this change should be done. I will review this issue when I'm going to create the next WAF release.
