### ISSUE TITLE
Some feeds show up as empty

### ISSUE THREAD

**Issue by Ma6nu5** [jbe2277/waf#6]
Hello Jürgen, many thanks for your newsreader! 

I was trying to move my feeds from another feedreader but a few of them turn up empty; Items: 0. When you have the time, please see if this is simple to fix.

https://w3techs.com/blogfeed/category/content_management 
https://images.videolan.org/videolan-news.rss
https://blog.todoist.com/feed/
http://sicilianhouses.com/sv/property/sicily/rss-2.0/
http://sicilianhouses.com/en/property/sicily/rss-2.0/
http://www.barnsrattigheter.com/feed/

VideoLAN in Feedreader

![image](https://user-images.githubusercontent.com/37984620/38176430-a39fd298-35e6-11e8-88fb-23b4514078a4.png)

VideoLAN in Jbe Newsreader

![image](https://user-images.githubusercontent.com/37984620/38176437-c9c3a5c6-35e6-11e8-85bf-39eb50ca5cc6.png)

Thanks again,
Magnus

**Comment by jbe2277** [comment]
Hello Magnus. Thanks a lot for your feedback. This issue is fixed in version 4.0.6.
