### ISSUE TITLE
What problem(s) does this solve?

### ISSUE THREAD

**Issue by ZachMierzejewski** [jbe2277/waf#7]
Holy cow, this is awesome!  You have put so much work into the best-practices guides, documenting your code, creating examples, structuring the project, packaging it, testing it, etc.  This rivals/beats many commercial products' user-friendliness.

But, I only realized that after downloading the code and going through the source code.  I spent ~10 minutes searching online to find what this package could actually do for me.  I wanted to know what I could potentially get before I invested in downloading it and opening another instance of VS.  (Which, I know sounds silly in retrospect, but it was a small barrier to entry.)

When reading the wiki, I thought you were just teaching what the patterns should look like and what you would need for WPF/MVVM development.

I found [this DZone article](https://dzone.com/articles/introducing-wpf-application) with a succinct list of what this could do.  That article is 6 years old and you've obviously been working hard on this since then.

You've done a ton of work and I appreciate it.  I'm not asking you to do this, but suggesting an improvement to the user experience:  **Will you create a succinct bullet-point list of these features (and maybe a short description of the problem they solve) and display it prominently in the README and wiki?**

What made it click in my head was BookLibrary.docx.  So, the bullet points could probably just be those headers and the other .docx headers.

Thank you for your hard work and time!

**Comment by jbe2277** [comment]
Thanks a lot for this positive feedback. I will consider your idea.

**Comment by sommmen** [comment]
Hi @jbe2277 I came across this library randomly, but it just so happens I use wpf for work aswell. I had a blast reading through the wiki - you have a talent for writing on point documentation. You did not go too deep nor too broad or too shallow - just perfect. I am just now going to use at least 3 things/principles i saw in there and it is extremely helpfull.

All I wanted to say was - thanks!

**Comment by jbe2277** [comment]
@sommmen: Thanks for your feedback.
