### ISSUE TITLE
Unable to add the feed of the company I work for :-)

### ISSUE THREAD

**Issue by Ma6nu5** [jbe2277/waf#9]
Hello Jürgen, 
I worry this may be my fault. The newsreader is not accepting http://wp3.spreadsheetconverter.com/feed/rss which is the RSS feed for the WordPress site that I edit. 
Can you please check? Maybe I did something wrong. 
Many thanks,
Magnus

**Comment by jbe2277** [comment]
The NewsReader App requires the Link element in RSS feeds. This element is missing in your feed.
